import { StyleSheet } from "react-native";
import {
  PRIMARY,
  BACKGROUND,
  CARD,
  TEXT,
  TEXT_MUTED,
  BORDER,
  TAG_BG,
  SUCCESS,
} from "./colors";

export const sharedStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: BACKGROUND },
  content: { padding: 20, paddingBottom: 40 },
  card: {
    backgroundColor: CARD,
    borderRadius: 12,
    padding: 20,
    borderWidth: 1,
    borderColor: BORDER,
    marginBottom: 16,
  },
  step: { fontSize: 12, color: TEXT_MUTED, fontWeight: "600", letterSpacing: 0.3 },
  title: { fontSize: 24, fontWeight: "800", color: TEXT, marginTop: 8, marginBottom: 6 },
  subtitle: { fontSize: 15, color: TEXT_MUTED, lineHeight: 22, marginBottom: 20 },
  input: {
    backgroundColor: TAG_BG,
    borderWidth: 1,
    borderColor: BORDER,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 8,
    fontSize: 15,
    color: TEXT,
    marginBottom: 14,
  },
  inputMultiline: { minHeight: 96, textAlignVertical: "top" },
  btnPrimary: {
    backgroundColor: PRIMARY,
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 8,
  },
  btnPrimaryText: { color: "#fff", fontWeight: "700", fontSize: 16 },
  btnOutline: {
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center",
    borderWidth: 1,
    borderColor: PRIMARY,
    marginBottom: 10,
    backgroundColor: CARD,
  },
  btnOutlineText: { color: PRIMARY, fontWeight: "700", fontSize: 15 },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: CARD,
  },
  chipActive: { backgroundColor: PRIMARY, borderColor: PRIMARY },
  chipText: { fontWeight: "600", color: TEXT },
  chipTextActive: { color: "#fff" },
  statCard: {
    flex: 1,
    backgroundColor: CARD,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: BORDER,
  },
  statValue: { fontSize: 22, fontWeight: "800", color: TEXT },
  statLabel: { color: TEXT_MUTED, fontSize: 13, marginTop: 4 },
  successBanner: {
    padding: 12,
    backgroundColor: "#ECFDF5",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: SUCCESS,
    marginTop: 12,
  },
  successText: { color: TEXT, fontWeight: "600" },
});
